### ISSUE TITLE
Committing built files

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/screens-viewer#2]
Do we want to commit built files to the master branch?

**Comment by AdaRoseCannon** [comment]
Yes, so that other modules can require it without having to additionally download babel to compile it on post install which is quite slow.
This has also been the way it has been done previously, I prefer it personally do you have any arguments for change?

**Comment by JakeChampion** [comment]
Having built files in the main branch makes diffs noisy. An approach that could alleviate the noisy diff but still allow requiring from Github without needed to have a post-install step would be to have a branch named `production` that contains the built files and has it's commits tagged and pushed to Github's releases page. What do you think to the idea?
